### ISSUE TITLE
Fix data storage

### ISSUE THREAD

**Issue by matdehaven** [VFCI/vfciBusinessCycles#23]
Some data files from large iterations of ~500 VAR model results are too big to store on Github.  Need solution.

I think the answer should be to not store that much information.

I'm actually leaning towards not storing any VAR model outputs, and instead making it very easy to remake sets of VAR models on the fly, as that doesn't actually take much compute time.

I think I will need to keep the summary statistics from when we run the big 500+ models iterations, as those do take some time to compute.

This is a big cleaning task.

**Comment by fernando-duarte** [comment]
Looks like since we have a "Teams Account", this is not a problem starting Oct 1, see [this](https://github.com/orgs/community/discussions/61362).

**Comment by matdehaven** [comment]
Solved by purchasing the higher tier of data storage.
