### ISSUE TITLE
Correlation of max-share and cholesky shocks high for all variables

### ISSUE THREAD

**Issue by matdehaven** [VFCI/vfciBusinessCycles#41]
We currently show that the VFCI-targeted shock is very similar to the shock to the VFCI from a Cholesky with VFCI ordered first (i.e. the reduced form residual of VFCI).  This fits nicely with our narrative.  So far, we have just looked at the IRFs.  I decided to take a look at the correlation of the raw shock series and to make the same comparison for each variable.

In each panel of the figure below, the x-axis shows the max-share shock targeting **that variable** at the BC frequency, the y-axis shows the first Cholesky shock with **that variable** ordered first.

So it turns out that every variable has this feature.  There are some differences if I start looking at different comparisons on IRFs or the contributions to realized values.

[corr-max-share-chol.pdf](https://github.com/VFCI/vfciBusinessCycles/files/14565471/corr-max-share-chol.pdf)

**Comment by matdehaven** [comment]
My first thought is that this makes the VFCI result less unique and that perhaps we should not include it in this draft of the paper.

I think this level of correlation of the reduced-form residuals with the max-share shocks has to also be squared with the high level of correlation we see among the max-share shocks targeting different variables (see Figure 7 in the paper).

It seems like we are arriving at a place where *everything* returns the business cycle.  In some ways, this makes sense.  All (most) of these variables comove with the business cycle, and the business cycle is probably both (1) the highest forecast error variation in BC frequencies and (2) the largest residual for each variable in the VAR.

I think actually there is a mathematical link between the max-share method and the Cholesky shock ordered first that might be worth working out.  I think the first Cholesky is the same as maximizing short-run (high frequency) FEV for that variable?

**Comment by fernando-duarte** [comment]
We should work it out more formally, yes. In a simple 2-by-2 VAR, I can see how targeting a horizon of 0 gives the same as Cholesky when Cholesky is the correct identification strategy. Once we go to frequency domain and Cholesky is not the true model, I am not so sure, but it can be worked out without too much pain I think. At an intuitive level, I don't see why there would be a strong relation between the shocks identified in the two different ways when Cholesky is not the right identification strategy, i.e., when one shock is not the dominant one contemporaneously by assumption.

Even though the high correlations b/w Cholesky shocks and max-share targeted shocks is something to explain, two shocks with 90% correlation can have very different IRF, and explain different shares of variances of different variables. We again run into the question of what measure is the right measure of "distance". In the end, to make the argument that two shocks are the same, all reasonable measures of distance should be close.

Either way is OK with me regarding whether to keep these results in the paper for this round. Although I do not see anything wrong, it is true that there is a lot to understand.

**Comment by matdehaven** [comment]
I am going to keep the Cholesky results in for this draft.

I will open a new longer term issue for us to address the larger question of comparing the Cholesky and max-share methods.
