### ISSUE TITLE
Edit Introduction

### ISSUE THREAD

**Issue by matdehaven** [VFCI/vfciBusinessCycles#42]
I am printing out the introduction in the morning to share at Macro breakfast on Wednesday, March 13.

@fernando-duarte, can you please read over the introduction and make final comments and edits?

If you are able to put in comments before the morning, I will try to review and resolve them before printing out copies.

**Comment by fernando-duarte** [comment]
I'm on it

**Comment by matdehaven** [comment]
I will see what I can do to make the polished in morning then.
