### ISSUE TITLE
Compare Cholesky and Max-share methods

### ISSUE THREAD

**Issue by matdehaven** [VFCI/vfciBusinessCycles#43]
We need to compare more completely the Cholesky ordered-first shock and the max-share shocks.

These end up looking very similar for all of the variables in the VAR.

I think that the Cholesky ordered-first shock is equivalent to targeting that variable's at the highest frequency.  See the FEVD for the Cholesky shocks.  It would be good to show this mathematically.  Also, would it then be equivalent to targeting a specific horizon in the time domain?

**Comment by fernando-duarte** [comment]
Merged with #65
