### ISSUE TITLE
Add financial variables to VAR

### ISSUE THREAD

**Issue by fernando-duarte** [VFCI/vfciBusinessCycles#70]
In the construction of the external VFCI, we use some financial variables (S&P returns and vol, liquidity, credit, term premia, etc.) and their principal components. Let's allow for these variables (the individual financial variables or the principal components) to be included in the VAR as exogenous variables.

Let's also allow them to be independent variables in the heteroskedasticity regression when constructing the internal VFCI.

**Comment by matdehaven** [comment]
Done
