### ISSUE TITLE
Add consumption/output lags in the construction of external VFCI

### ISSUE THREAD

**Issue by fernando-duarte** [VFCI/vfciBusinessCycles#71]
The external VFCI uses the principal components of financial variables as independent variables in both the mean and the vol equations.

Let's allow for lags of consumption and output growth to be included as independent variables in both the mean and vol regressions.

When lags of consumption/output growth are included in the vol regression 

$$\log \text{error}^2 = a + b \ PC + c \ \text{Lags of cons/output growth} + \varepsilon$$

the VFCI can be constructed as:

- [x] The fitted value of the regression $VFCI = \hat{a} + \hat{b} \ PC + \hat{c} \ \text{Lags of cons/output growth}$
- [x] The fitted value ignoring the terms with lags of consumption/output growth $VFCI = \hat{a} + \hat{b} \ PC$

(or in the original way in which we don't include the lags for cons/output growth in vol equation)

**Comment by matdehaven** [comment]
Done.  These two options look very similar to our baseline vfci without the lags.
